import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white antialiased">
        <header className="border-b border-zinc-800 p-4 flex justify-between items-center bg-zinc-900/50 backdrop-blur-md sticky top-0 z-50">
          <a href="/" className="font-bold text-xl tracking-tighter">GHOST<span className="text-blue-500">PLATFORM</span></a>
          <div className="text-[10px] bg-blue-500/10 text-blue-400 px-2 py-1 rounded border border-blue-500/20 uppercase font-mono">
            Agent active
          </div>
        </header>

        {/* TOP AD SLOT - Replace the 'src' with your Adsterra script URL */}
        <div className="max-w-4xl mx-auto my-4 min-h-[90px] flex items-center justify-center">
          <Script 
            id="adsterra-top"
            src="//pl21000000.highperformanceformat.com/..." // Paste your Adsterra script source here
            strategy="lazyOnload"
          />
        </div>

        <main>{children}</main>

        {/* BOTTOM AD SLOT */}
        <footer className="mt-20 border-t border-zinc-800 p-12 bg-zinc-900/30">
          <div className="max-w-4xl mx-auto flex flex-col items-center">
             <div className="w-full min-h-[250px] flex items-center justify-center mb-8">
               <Script 
                 id="adsterra-bottom"
                 src="//pl21000000.highperformanceformat.com/..." // Paste your bottom ad source here
                 strategy="lazyOnload"
               />
             </div>
             <p className="text-zinc-600 text-sm">© 2026 Ghost Platform. Generated by AI Agent.</p>
          </div>
        </footer>
      </body>
    </html>
  )
}