import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script';
import AdUnit from '@/components/AdUnit';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="h3aCKZviqx-Idv9CJQrru8ILdn473bGKkgbERIJSzHY" />
        {/* SOCIAL BAR / POP-UNDER SCRIPT */}
        <Script 
          id="adsterra-social-bar"
          src="//pl21000000.highperformanceformat.com/..." 
          strategy="lazyOnload" 
        />
      </head>
      <body className="bg-black text-white antialiased">
        <header className="border-b border-zinc-800 p-4 flex justify-between items-center bg-zinc-900/50 backdrop-blur-md sticky top-0 z-50">
          <a href="/" className="font-bold text-xl tracking-tighter">GHOST<span className="text-blue-500">PLATFORM</span></a>
          <div className="text-[10px] bg-blue-500/10 text-blue-400 px-2 py-1 rounded border border-blue-500/20 uppercase font-mono">
            Agent active
          </div>
        </header>

        {/* TOP AD - Replace with your actual Zone ID */}
        <Script
          id="native-banner-top"
          src="https://consumptionbackwardsentiments.com/b1aff45fccdd6bc09be1b32e952be658/invoke.js"
          async
          strategy="afterInteractive"
        />
        <div id="container-b1aff45fccdd6bc09be1b32e952be658"></div>
        <AdUnit zoneId="28816518" />

        <main>{children}</main>

        {/* BOTTOM AD - Replace with your actual Zone ID */}
        <Script id="adunit-bottom-opts" strategy="afterInteractive">
          {`atOptions = {
            'key' : 'b28d6259d584a85eaf96ca087c785b74',
            'format' : 'iframe',
            'height' : 90,
            'width' : 728,
            'params' : {}
          };`}
        </Script>
        <Script
          id="native-banner-bottom"
          src="https://consumptionbackwardsentiments.com/b28d6259d584a85eaf96ca087c785b74/invoke.js"
          strategy="afterInteractive"
        />
        <AdUnit zoneId="28816522" />

        <footer className="p-10 border-t border-zinc-800 text-center">
          <p>© 2026 Ghost Platform - Automated Revenue</p>
        </footer>
      </body>
    </html>
  )
}